server {
    listen 9080;
    server_name host1;
    client_max_body_size 10M;
    location / {
        root ./www;
        methods GET POST;
        index index.html;
        directory_listing on;
    }
}

server {
    listen 9080;
    server_name host2;
    client_max_body_size 10M;
    location / {
        root ./www2;
        methods GET POST;
        index index_copy.html;
        directory_listing on;
    }
}

